### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by craiga** [anx-ckreuzberger/django-request-cache#2]
Thanks so much for making this available!

Would be great to get a new release so that we can easily make use of @int-ua's `MiddlewareMixin` changes from PR #1.

At the moment I need to add the following to my `requirements.txt`:

```
-e git+git://github.com/anx-ckreuzberger/django-request-cache.git@bd007d24afb22191eb6d83fe5473a7f7f1bcdc70#egg=django-request-cache
```

**Comment by anx-ckreuzberger** [comment]
Version 1.1 has been published to pypi: https://pypi.org/project/django-request-cache/

**Comment by craiga** [comment]
Thank you!
